### ISSUE TITLE
Is there no bayeswave_plot? Because I can't find megaplot.py and megasky.py.

### ISSUE THREAD

**Issue by WuShichao** [conda-forge/bayeswave-feedstock#3]
Issue:  I can't find megaplot.py and megasky.py.

**Comment by duncanmmacleod** [comment]
@WuShichao, can you post a little more information? What are you expecting to see, and in which paths, and what do you actually see?

**Comment by WuShichao** [comment]
@duncanmmacleod I forgot bayeswaveutils. Now it works. By the way, which version of lalsuite did LIGO use with BayesWave (O2/git-stable version)? I notice that megasky.py in O2 version uses sky_area, which requires an old version of lalsuite.

**Comment by duncanmmacleod** [comment]
@astroclark?

**Comment by astroclark** [comment]
Many of the previous analyses were conducted with versions from the old SVN repository or from before moving to the semantic versioning.  The transition to `ligo.skymap` away from `sky_area` has indeed broken some of the sky map functionality but we have a fix in master.  The recent releases have largely been used to test and understand how to use the conda packaging (See e.g. the release notes: https://git.ligo.org/lscsoft/bayeswave/releases). BayesWave is currently nearing the end of review, pending some checkpointing issues in condor and fixing the calls to megasky - we expect a new, stable release near the end fo this week/early next week

**Comment by WuShichao** [comment]
@astroclark Thanks and good luck! So you don't remember which version of lalsuite was used in O2? I compile BayesWave (stable/O2 version) from source code on LIGO's Gitlab, sky_area conflicts with new lalsuite which I've installed, so I can't use meagsky.py.
Maybe I should just use the next new stable release?

**Comment by astroclark** [comment]
If you can wait a few days (hopefully less than a week or so), then i would certainly recommend using the upcoming, reviewed O3 release, yes.  To repeat O2 analyses, though, i think you will at least need the `lalinference_o2` branch of lalsuite.

**Comment by WuShichao** [comment]
@astroclark Thank you, Clark!

**Comment by astroclark** [comment]
@WuShichao I apologise for the delay, it took longer than expected to solve some condor checkpointing issues.   I believe we now have a solution so we should be in a position for a new bayeswave release & documentation very soon.  Thank you for your patience.

**Comment by WuShichao** [comment]
@astroclark Don't apologize ~ You're doing a great job. I'll wait for the new BayesWave & its documentation:)

**Comment by duncanmmacleod** [comment]
@astroclark, is this resolved with the new bayeswave 1.0.3 release?
